name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java: [ '8', '11', '15' ]

    name: Java ${{ matrix.java }}

    steps:
    - uses: actions/checkout@v2
    - uses: gradle/wrapper-validation-action@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set encoding and print version information
      run: |
        export LANG=C.UTF-8
        locale
        ./gradlew --version
    - name: Build plugin
      run: ./gradlew build
    - name: Run integration test
      working-directory: ./integration-test
      run: ../gradlew build
